### PR TITLE
AlgoHeist21: Selection Sort Algorithm

### PR DESCRIPTION
**Pull request by Rimpi246**
# HacktoberFest 21

`AlgoHeist21: Selection Sort Algorithm`

## Algorithm you like to add

Selection Sort

## Programming Language for Algorithm Implementation

C++

## Code file name with extension

ascSelectionSort.cpp

## Did you watched Money Heist

No

## YOU ARE

a student 

## GITHUB USERNAME

Rimpi246

### We are looking for a name for this repository for next hacktober fest please suggest below (optional)

`AlgoHeist`

Thanks for your contributions !!

### CODE REVIEW

**Review by GauravWalia19 — CHANGES_REQUESTED** [review]
Please update the README

**Comment by Rimpi246** [comment]
@GauravWalia19  I did make some changes in the Readme, could you please elaborate what changes I need to make exactly ?

**Comment by Rimpi246** [comment]
@GauravWalia19 Readme updated

**Comment by GauravWalia19** [comment]
Can you please resend the clean PR this has conflicts and wrong README updates that is not acceptable

**Pull request closed without merging**
