### PR TITLE
added Bubble Sort in Golang

### LINKED ISSUE #111: Golang in BUBBLE-SORT
At the moment, there's no folder for Golang inside the BUBBLE-SORT. So, it'd be great if we could have it there.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by GauravWalia19** [comment]
Can you please create a issue for this with **HacktoberFest20** template

**Review by GauravWalia19 — CHANGES_REQUESTED** [review]
Please update the README also

**Comment by randiltennakoon** [comment]
Cool, I will update the README

**Review by ghost — COMMENTED** [review]
I updated README

**Review by GauravWalia19 — APPROVED** [review]

**Pull request merged**
