### PR TITLE
AlgoHeist22: string subsequence

### PR DESCRIPTION
**Pull request by naaam-h-siddhu**
# HacktoberFest 22

Please mention the PR subject as `AlgoHeist22: Algorithm Name`

## Algorithm you like to add

subsequence generation of string in c++

## Programming Language for Algorithm Implementation

c++

## Code file name with extension

subsequence.cpp

## Did you watched Money Heist

Yes 

### If Yes, mention your favourite character (optional)

Berlin

## YOU ARE

student

## GITHUB USERNAME

naaam-h-siddhu

### We are looking for a name for this repository for the next hacktober fest please suggest below (optional)

`_____________`

Thanks for your contributions !!

### CODE REVIEW

**Review by GauravWalia19 — CHANGES_REQUESTED** [review]
Code seems to be okay, can you please update the README

**Comment by naaam-h-siddhu** [comment]
Done 👍

**Comment by naaam-h-siddhu** [comment]
Done 👍

**Review by GauravWalia19 — APPROVED** [review]
All good !!

**Comment by naaam-h-siddhu** [comment]
🤟🏻

**Pull request merged**
